[config]
# If set to enabled, it will check for updates when you run the matugen command, notifying you that an update is avaiable.
# WARNING: Matugen needs to be compiled with the `update-informer` feature for this to work.
version_check = false

# The color which should be used as the source_color if no good color was found from an image.
# Can be defined in any css format.
# The cli flag will override this if used.
fallback_color = "#ffbf9b"

# Which color to choose if multiple good colors were found from an image.
# choices: [darkness, lightness, saturation, less-saturation, value, closest-to-fallback]
# The cli flag will override this if used.
prefer = "closest-to-fallback"

# Enables caching which will cache the colorscheme, custom colors, etc. into a cache folder located in
# Windows: C:\Users\user\AppData\Roaming\InioX\matugen\cache\images\<file>
# Linux: $XDG_CACHE_HOME/matugen/<file> or $HOME/.cache/matugen/images/<file>
# MacOS: $HOME/Library/Caches/matugen/images/<file>
# The file follows this naming: <image_name>.<image_extension>.<image_hash>.json
# For example: testimage.png.0cfd2d624b3d09bf6246b7be9ca79e207e7aa1189d961d44949628b99811bb9d.json
# You can modify the cache and it will then be loaded when using the same image.
# The colors are defined using the #RRGGBBAA format.
caching = true

# Changing the syntax
# Expr is for keywords like {{ <keyword> }}
expr_prefix = "{{"
expr_postfix = "}}"

# Block is for stuff like for loops etc.
block_prefix = "<*"
block_postfix = "*>"

# Imports json files just like `--import-json` does.
# Relative paths will be resolved from the path `config.toml` is in.
import_json_files = []

# Defaults to the contrast from CLI if unspecified.
# Value from -1 to 1. 
# -1 represents minimum contrast, 0 represents standard (i.e. the design as spec'd),
# and 1 represents maximum contrast.
contrast = 0.0

[config.wallpaper]
# Whether to set the wallpaper or not
set = false

# The base command to run for applying the wallpaper.
# Keywords like {{ image }} or anything that works inside of hooks works here.
# You could also set a static color if you use the color keywords and the wallpaper setter supports it.
command = "awww img --transition-type center {{ image }}"

# For example, killing the wallpaper daemon. Usage is like a normal hook.
# pre_hook = ""

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"
post_hook = "pkill -USR2 btop || true"

[templates.dunst]
input_path = "~/.config/matugen/templates/dunst"
output_path = "~/.config/dunst/dunstrc"
post_hook = "dunstctl reload"

[templates.foot]
input_path = "~/.config/matugen/templates/foot.ini"
output_path = "~/.config/foot/colors.ini"

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = "~/.config/fuzzel/colors.ini"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-3.0.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = "gsettings set org.gnome.desktop.interface gtk-theme ''; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}"

# [templates.gtk3-20]
# input_path = "~/.config/matugen/templates/gtk-3.20.css"
# output_path = ~/.config/gtk-

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-4.0.css"
output_path = "~/.config/gtk-4.0/colors.css"
post_hook = "~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/land/colors.lua"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock/colors.conf"

[templates.neovim]
input_path = "~/.config/matugen/templates/neovim.lua"
output_path = "~/.config/nvim/lua/smooll/plugins/mini/base16.lua"

[templates.qt]
input_path = "~/.config/matugen/templates/Qt.colors"
output_path = "~/.local/share/color-schemes/Matugen.colors"

[templates.spicetify]
input_path = "~/.config/matugen/templates/spicetify.ini"
output_path = "~/.config/spicetify/Themes/Sleek/color.ini"
post_hook = "spicetify apply"
