# Systemd stuff
exec-once = dbus-update-activation-environment --systemd -all
exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME
exec-once = systemctl --user start hyprpolkitagent

# Daemons
exec-once = playerctld daemon
exec-once = udiskie -a

# Hyprland
exec-once = hyprctl setcursor Bibata-Modern-Classic $cursor_size
exec-once = hypridle
# exec-once = hyprpaper
exec-once = hyprsunset

# Wallpaper
# exec-once = pwall
exec-once = waypaper --restore

# Quickshell
exec-once = sscli -s ndd

# Tray applets
exec-once = nm-applet
exec-once = blueman-applet
exec-once = copyq

# Misc
exec-once = flatpak run com.discordapp.Discord
exec-once = spotify
# exec-once = steam
