hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XCURSOR_SIZE", "$cursor_size")
hl.env("HYPRCURSOR_SIZE", "$cursor_size")
hl.env("QT_QPA_PLATFORMTHEME", "hyprqt6engine")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
