# See https://wiki.hypr.land/Configuring/Monitors/
monitor = eDP-1, highres, 0x0, 1
# monitor = eDP-1, 1280x720, 0x0, 1
# monitor = eDP-1, 1024x720, 0x0, 1
# monitor = eDP-1, 1024x768, 0x0, 1
# monitor = eDP-1, 864x486, 0x0, 1
# monitor = eDP-1, 800x600, 0x0, 1
