# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Open app in a floating window
windowrule = float on, match:class org.gnome.eog

# Open app on specified workspace
windowrule = workspace 2, match:class zen
windowrule = workspace 3, match:class spotify
windowrule = workspace 3, match:initial_title ^FL Studio 2025$
windowrule = workspace 4, match:class gimp
windowrule = workspace 4, match:class org.inkscape.Inkscape
windowrule = workspace 4, match:class Aseprite
windowrule = workspace 5, match:class thunar
windowrule = workspace 6, match:class steam
windowrule = workspace 6, match:class net.lutris.Lutris
windowrule = workspace 7, match:class org.qbittorrent.qBittorrent
windowrule = workspace 7, match:class com.github.wwmm.easyeffects
windowrule = workspace 8, match:class discord
windowrule = workspace 9, match:class com.obsproject.Studio

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule {
    name = fix-dragging-xwayland
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Prevent apps like hypridle from firing if the currently focused app is in fullscreen mode
windowrule = idle_inhibit fullscreen, match:focus true

# Center all windows except ones with initialClass = steam_proton
windowrule = center on, match:initial_class negative:steam_proton
