$outer_color = {{colors.primary.default.rgba}} {{colors.on_primary.default.rgba}} 45deg
$check_color = {{colors.secondary.default.rgba}} {{colors.on_secondary.default.rgba}} 120deg
$fail_color = {{colors.tertiary.default.rgba}} {{colors.on_tertiary.default.rgba}} 40deg
$font_color = {{colors.on_surface.default.rgb}}
