set -g @tmux-dotbar-bg "{{colors.surface.default.hex}}"
set -g @tmux-dotbar-fg "{{colors.outline_variant.default.hex}}"
set -g @tmux-dotbar-fg-current "{{colors.primary.default.hex}}"
set -g @tmux-dotbar-fg-session "{{colors.outline_variant.default.hex}}"
set -g @tmux-dotbar-fg-prefix "{{colors.secondary.default.hex}}"
