# colors for fuzzel application launcher
# You can use this template by adding the following to wallust.toml:
# fuzzel = { template = "fuzzel.ini", target = "~/.config/fuzzel/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/fuzzel/colors.ini


[colors]
background=#100F17ff
text=#FEEBE1ff
prompt=#3B3A44ff
placeholder=#B33640ff
input=#BB3933ff
match=#BF412Aff
selection=#BE532Dff
selection-text=#DF7A4Dff
selection-match=#F8382Fff
counter=#F6DBCBff
border=#AC998Eff
