MODULES=()
BINARIES=()
FILES=()
# HOOKS=(plymouth base systemd autodetect microcode keyboard keymap modconf block filesystems fsck)
HOOKS=(base systemd autodetect microcode keyboard keymap modconf block filesystems fsck)
