$outer_color = rgba({{color9 | rgb}},1.0) rgba({{color14 | rgb}},1.0) 45deg
$check_color = rgba({{color9 | complementary | rgb}},1.0) rgba({{color10 | complementary | rgb}},1.0) 120deg
$fail_color = rgba({{color13 | rgb}},1.0) rgba({{color10 | rgb}},1.0) 40deg
$font_color = rgb({{foreground | rgb}})
