[wallust]
; accent             = 1db954
accent             = {{color8 | strip}}
accent-active      = {{color9 | strip}}
accent-inactive    = {{color1 | strip}}
banner             = {{color8 | strip}}
border-active      = {{color9 | strip}}
border-inactive    = {{color1 | strip}}
header             = {{color8 | strip}}
highlight          = {{color13 | strip}}
main               = {{background | strip}}
notification       = {{color11 | strip}}
notification-error = {{color3 | strip}}
subtext            = {{color16 | strip}}
text               = {{foreground | strip}}
