# colors for foot terminal
# You can use this template by adding the following to wallust.toml:
# foot = { template = "foot.ini", target = "~/.config/foot/colors.ini" }
# and add the following to your foot.ini config
#
# [main]
# include=/home/USERNAME/.config/foot/colors.ini


[colors-dark]
background=100F17
foreground=FEEBE1

# Normal/regular colors (color palette 0-7)
regular0=3B3A44  # black
regular1=B33640  # red
regular2=BB3933  # green
regular3=BF412A  # yellow
regular4=BE532D  # blue
regular5=BE6037  # magenta
regular6=BE6D3F  # cyan
regular7=F6DBCB  # white

# Bright colors (color palette 8-15)
bright0=AC998E   # bright black
bright1=DE3845   # bright red
bright2=F04139   # bright green
bright3=FF5638   # bright yellow
bright4=FE6D3C   # bright blue
bright5=FE7F49   # bright magenta
bright6=FD9254   # bright cyan
bright7=F6DBCB   # bright white

# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# urls=<regular3>
