theme {
    color_scheme = /home/skowriii/.local/share/color-schemes/Matugen.colors

    icon_theme = kora

    style = Darkly

    font = Montserrat
    font_size = 12
}

misc {
    single_click_activate = false
}
