#!/usr/bin/env bash

source "$(dirname "$0")/variables"

function install_yay()
{
    if ! command -v yay &>/dev/null; then
        S_LOG "yay not found! Installing..."
        S_CLONE https://aur.archlinux.org/yay-bin.git
        cd yay-bin
        makepkg -si
        cd ../
        rm -rf yay-bin

        S_LOG "yay installed!"
    fi
}

function install_decman()
{
    if ! command decman &>/dev/null; then
        S_LOG "decman not found! Installing..."
        yay -S --needed decman

        S_LOG "decman installed!"
    fi
}

function check_preinstalled_packages()
{
    local packages=( \
        python3 \
        reflector \
        python-requests \
        python-py-notifier \
    )

    local missing_packages=""

    S_LOG "Checking for missing packages..."
    for package in "${packages[@]}"; do
        missing_packages+="$package "
    done

    if [[ -n "$missing_packages" ]]; then
        S_LOG "Installing missing packages..."
        yay -S --needed $missing_packages
    fi
}

function setup_base()
{
    S_LOG "Creating grub config..."
    sudo grub-mkconfig -o "/boot/grub/grub.cfg"

    S_LOG "Adding /tmp tmpfs entry to /etc/fstab..."
    echo "tmpfs /tmp tmpfs defaults,noatime,mode=1777 0 0" | sudo tee -a /etc/fstab

    S_LOG "Modifying / entry in /etc/fstab..."
    sudo sed -i -E \
        "s@^(UUID=[^[:space:]]+[[:space:]]+/[[:space:]]+ext4[[:space:]]+)[^[:space:]]+@\\1rw,relatime,lazytime,commit=60,journal_async_commit@" \
        /etc/fstab

    S_LOG "Setting up UKIs..."
    sudo mkdir -p /boot/EFI/Linux

    sudo mkinitcpio -P

    S_LOG "Creating efibootmgr entry for linux kernel UKI..."
    sudo efibootmgr \
        --create \
        --disk /dev/nvme0n1 \
        --part 1 \
        --label "Arch Linux" \
        --loader "\EFI\Linux\arch-linux.efi" \
        --unicode

    S_LOG "Creating efibootmgr entry for linux-zen kernel UKI..."
    sudo efibootmgr \
        --create \
        --disk /dev/nvme0n1 \
        --part 1 \
        --label "Arch Linux Zen" \
        --loader "\EFI\Linux\arch-linux-zen.efi" \
        --unicode

    S_LOG "Setting up nbfc..."
    S_DRY sudo systemctl enable nbfc_service --now
    S_DRY sudo nbfc update
    S_DRY sudo nbfc config -a "$S_NBFC_MODEL"
    S_DRY sudo nbfc set -a

    S_LOG "Disabling NetworkManager-wait-online.service"
    sudo systemctl disable NetworkManager-wait-online.service
}

main()
{
    # S_LOG "$S_USERNAME" | sudo -E -- tee -a /etc/sudoers >/dev/null
    # trap 'sudo -E -- sed -i "/^${S_USERNAME}/d" /etc/sudoers' EXIT

    install_yay

    check_preinstalled_packages

    install_decman

    S_LOG "Dry running decman to check for errors..."

    if ! sudo decman --source /personal/dotfiles/decman/decman.py --dry-run; then
        exit 1
    fi

    S_LOG "No errors found, running for real this time..."

    rm -rf ${HOME}/.config/yay

    sudo decman --source /personal/dotfiles/decman/decman.py

    setup_base

    $(dirname "$0")/shell

    S_LOG "Setup done! Enjoy!"
}

main
